name: myenv
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - absl-py=1.2.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.11.0
  - anaconda-navigator=2.3.0
  - anaconda-project=0.11.1
  - argh=0.26.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asn1crypto=1.5.1
  - astroid=2.11.7
  - astropy=5.1
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.5.4
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - bitarray=2.5.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.4.3
  - boto=2.49.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.5
  - conda=23.1.0
  - conda-build=3.20.5
  - conda-content-trust=0.1.3
  - conda-env=2.6.0
  - conda-pack=0.6.0
  - conda-package-handling=1.9.0
  - conda-repo-cli=1.0.5
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextlib2=21.6.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - curl=7.84.0
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.11.0
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.4
  - distributed=2022.7.0
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - fastcache=1.1.0
  - fftw=3.3.9
  - filelock=3.6.0
  - flake8=3.8.4
  - flask=2.1.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - frozenlist=1.3.1
  - fsspec=2022.7.1
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - glob2=0.7
  - gmpy2=2.1.2
  - google-auth=2.11.0
  - google-auth-oauthlib=0.4.6
  - greenlet=1.1.1
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.3
  - imageio=2.19.3
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.17.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - keyring=23.4.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lerc=3.0
  - libarchive=3.6.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.84.0
  - libdeflate=1.8
  - libiconv=1.16
  - liblief=0.11.5
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.38.0
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=3.1.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mccabe=0.6.1

  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.2.1
  - msgpack-python=1.0.3
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - navigator-updater=0.2.1
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - nose=1.3.7
  - notebook=6.4.12
  - numba=0.55.1
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - numpydoc=1.4.0
  - oauthlib=3.2.1
  - olefile=0.46
  - opencv=4.0.1
  - openpyxl=3.0.10
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.4
  - pandoc=2.12
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.7.0
  - partd=1.2.0
  - path=16.2.0
  - path.py=12.5.0
  - pathlib=1.0.1
  - pathlib2=2.3.6
  - pathtools=0.1.2
  - patsy=0.5.2
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - pkginfo=1.8.2
  - platformdirs=2.5.2
  - plotly=5.11.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-lief=0.11.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycurl=7.45.1
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.2.0
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pylint=2.14.5
  - pynacl=1.5.0
  - pyodbc=4.0.34
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=7.1.2
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - regex=2022.7.9
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rope=0.22.0
  - rsa=4.9
  - rtree=0.9.7
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.100
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=63.4.1
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=5.0.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlalchemy=1.4.39
  - sqlite=3.39.2
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - sympy=1.10.1
  - tbb=2021.5.0
  - tblib=1.7.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.11.2
  - torchaudio=0.12.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - ujson=5.4.0
  - unicodecsv=0.14.1
  - urllib3=1.26.11
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.7.2
  - zeromq=4.3.4
  - zict=2.1.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.5.2
  - pip:
      - accelerate==0.17.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.4.0
      - av==8.0.3
      - box2d-py==2.3.5
      - colabcode==0.3.0
      - diffusers==0.14.0
      - einops==0.6.0
      - fvcore==0.1.5.post20210924
      - gurobipy==9.1.1
      - gym==0.26.1
      - gym-notices==0.0.8
      - h11==0.12.0
      - huggingface-hub==0.13.2
      - hyperopt==0.2.7
      - imageio-ffmpeg==0.4.5
      - imhist==0.0.4
      - imwatermark==0.0.2
      - iopath==0.1.9
      - jupyter-server==1.13.1
      - jupyterlab==3.0.7
      - jupyterlab-server==2.8.2
      - lightning-utilities==0.8.0
      - nbclassic==0.3.4
      - nest-asyncio==1.4.3
      - omegaconf==2.3.0
      - opencv-python==4.5.1.48
      - parameterized==0.8.1
      - portalocker==2.3.2
      - py4j==0.10.9.5
      - pygame==2.1.0
      - pyglet==1.5.21
      - pyngrok==5.1.0
      - pyspark==3.3.0
      - pytorch-lightning==2.0.0
      - pytorchvideo==0.1.3
      - safetensors==0.3.0
      - swig==4.1.0
      - tabulate==0.8.9
      - tenacity==8.1.0
      - termcolor==1.1.0
      - tokenizers==0.13.2
      - torch==1.7.1
      - torch-tb-profiler==0.4.0
      - torchmetrics==0.11.4
      - torchtest==0.5
      - torchvision==0.11.3
      - transformers==4.27.1
      - uvicorn==0.13.1
      - websocket-client==1.2.3
      - yacs==0.1.8
